AgendaContatos/Models/ContatoModel.cs
using System.ComponentModel.DataAnnotations;

namespace AgendaContatos.Models
{
    public class ContatoModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage ="Digite o nome docontato")]
        public string Nome { get; set; }


        [Required(ErrorMessage = "Digite o e-mail docontato")]
        [EmailAddress(ErrorMessage = "O e-mail informado não é valido")]
        public string Email { get; set; }
         


        [Required(ErrorMessage = "Digite o Celular docontato")]
        [Phone(ErrorMessage ="O celular informado não é valido")]
        public string Celular { get; set; }
    }
}

AgendaContatos/Models/ErrorViewModel.cs
using System;

namespace AgendaContatos.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AgendaContatos/Models/UsuarioModel.cs
using AgendaContatos.Enums;
using System;
using System.ComponentModel.DataAnnotations;

namespace AgendaContatos.Models
{
    public class UsuarioModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Digite o nome do Usuário")]
        public string Nome { get; set; }

        [Required(ErrorMessage = "Digite o Login")]
        public string Login { get; set; }


        [Required(ErrorMessage = "Digite o e-mail docontato")]
        [EmailAddress(ErrorMessage = "O e-mail informado não é valido")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Digite a senha do Usuário")]
        public string Senha { get; set; }


        public DateTime DataCadastro { get; set; }
        public DateTime? DataAtualização { get; set; }
        public PerfilEnum Perfil { get; set; }



    }
}

AgendaContatos/Controllers/ContatoController.cs
using AgendaContatos.Models;
using AgendaContatos.Repositorio;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace AgendaContatos.Controllers
{
    public class ContatoController : Controller
    {
        private readonly IContatoRepositorio contatoRepositorio;

        public ContatoController(IContatoRepositorio contatoRepositorio)
        {
            this.contatoRepositorio = contatoRepositorio;
        }

        public IActionResult Index()
        {
            List<ContatoModel> contatos = contatoRepositorio.BuscarTodos();
            return View(contatos);
        }



        [HttpGet]
        public IActionResult Criar()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Criar(ContatoModel contato)
        {
            try
            {

                if (ModelState.IsValid)
                {
                    contatoRepositorio.Adicionar(contato);
                    TempData["MensagemSucesso"] = "Contato cadastrado comsucesso!";
                    return RedirectToAction("Index");
                }


                return View(contato);
            }

            catch (System.Exception erro)
            {
                TempData["MensagemErro"] = $"Ops, não conseguimos cadastrar seu Contato, tente novamente, detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }


        [HttpGet]
        public IActionResult Editar(int id)
        {
            ContatoModel contato = contatoRepositorio.ListarPorId(id);
            return View(contato);
        }


        [HttpPost]
        public IActionResult Alterar(ContatoModel contato)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    contatoRepositorio.Atualizar(contato);

                    TempData["MensagemSucesso"] = "Contato alterado com comsucesso!";
                    return RedirectToAction("Index");
                }

                return View("Editar", contato);
            }
            catch (System.Exception erro)
            {
                TempData["MensagemErro"] = $"Ops, não conseguimos atualizar seu Contato, tente novamente, detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }

        }


        public IActionResult ApagarConfirmacao(int id)
        {
            ContatoModel contato = contatoRepositorio.ListarPorId(id);
            return View(contato);

        }

        public IActionResult Apagar(int id)
        {
            try
            {
               bool apagado = contatoRepositorio.Apagar(id);
                if (apagado)
                {
                    TempData["MensagemSucesso"] = "Contato apagado com comsucesso!";
                }
                else
                {
                    TempData["MensagemErro"] = "Ops, não conseguimos apagar seu contato!";
                }
                return RedirectToAction("Index");
            }
            catch (System.Exception erro)
            {
                TempData["MensagemErro"] = $"Ops, não conseguimos apagar seu Contato, mais detalhes do erro: {erro.Message}";
                return RedirectToAction("Index");
            }

        }
    }
}

AgendaContatos/Controllers/HomeController.cs
using AgendaContatos.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace AgendaContatos.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AgendaContatos/Controllers/UsuarioController.cs
using AgendaContatos.Models;
using AgendaContatos.Repositorio;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace AgendaContatos.Controllers
{
    public class UsuarioController : Controller
    {
        private readonly IUsuarioRepositorio usuarioRepositorio;

        public UsuarioController(IUsuarioRepositorio usuarioRepositorio)
        {
            this.usuarioRepositorio = usuarioRepositorio;
        }
        public IActionResult Index()
        {
            List<UsuarioModel> Usuarios = usuarioRepositorio.BuscarTodos();
            return View(Usuarios);
        }

        [HttpGet]
        public IActionResult Criar()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Criar(UsuarioModel usuario)
        {
            try
            {

                if (ModelState.IsValid)
                {
                    usuarioRepositorio.Adicionar(usuario);
                    TempData["MensagemSucesso"] = "Usuário cadastrado comsucesso!";
                    return RedirectToAction("Index");
                }


                return View(usuario);
            }

            catch (System.Exception erro)
            {
                TempData["MensagemErro"] = $"Ops, não conseguimos cadastrar seu Usuário, tente novamente, detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }


        }

        [HttpGet]
        public IActionResult Editar(int id)
        {
            UsuarioModel usuario = usuarioRepositorio.ListarPorId(id);
            return View(usuario);
        }

        public IActionResult ApagarConfirmacao(int id)
        {
            UsuarioModel usuario = usuarioRepositorio.ListarPorId(id);
            return View(usuario);

        }

        public IActionResult Apagar(int id)
        {
            try
            {
                bool apagado = usuarioRepositorio.Apagar(id);
                if (apagado)
                {
                    TempData["MensagemSucesso"] = "Usuário apagado com comsucesso!";
                }
                else
                {
                    TempData["MensagemErro"] = "Ops, não conseguimos apagar seu Usuário!";
                }
                return RedirectToAction("Index");
            }
            catch (System.Exception erro)
            {
                TempData["MensagemErro"] = $"Ops, não conseguimos apagar seu Usuário, mais detalhes do erro: {erro.Message}";
                return RedirectToAction("Index");
            }

        }

    }
}

AgendaContatos/Views/Contato/ApagarConfirmacao.cshtml
@model ContatoModel
@{
    ViewData["Title"] = "Confirmaçãoapagar ocontato";
}
<div class="text-center">
    <h3>Deseja apagar o contato realmente(@Model.Nome)?</h3>
</div>
<a class="btn btn-primary btn-block" role="button" asp-controller="contato" asp-action="Index">Cancelar exclusão</a>
<a class="btn btn-danger btn-block" role="button" asp-controller="contato" asp-action="Apagar" asp-route-id="@Model.Id">Confirmar exclusão</a>

AgendaContatos/Views/Contato/Criar.cshtml
@model ContatoModel

@{
    ViewData["Title"] = "Criar contato";
}

<div class="text-center">

    <h1 class="display-4">Cadastrar Contato</h1>
</div>

<form asp-controller="contato" asp-action="Criar" method="post">

    <div class="form-group">
        <label for="nome">Nome</label>
        <input type="text" asp-for="Nome" class="form-control" placeholder="Dogite o nome " />
        @Html.ValidationMessageFor(x => x.Nome)
    </div>

    <div class="form-group">
        <label for="email">E-mail</label>
        <input type="text" asp-for="Email" class="form-control" placeholder="Dogite o e-mail " />
        @Html.ValidationMessageFor(x => x.Email)
    </div>

    <div class="form-group">
        <label for="celular">Celular</label>
        <input type="text" asp-for="Celular" class="form-control" placeholder="Dogite o celular " />
        @Html.ValidationMessageFor(x => x.Celular)
    </div>

    <button type="submit" class="btn btn-primary btn-block">Adicionar</button>
    <a class="btn btn-secondary btn-block" asp-controller="contato" asp-action="Index" role="button">Voltar</a>


</form>

AgendaContatos/Views/Contato/Editar.cshtml
@model ContatoModel
@{
    ViewData["Title"] = "Editar contato";
}
<div class="text-center">
    <h1 class="display-4">Editar Contato</h1>
</div>

<form asp-controller="contato" asp-action="Alterar" method="post">
    
    <input type="hidden" asp-for="Id" />

    <div class="form-group">
        <label for="nome">Nome</label>
        <input type="text" asp-for="Nome" class="form-control" placeholder="Dogite o nome " />
        @Html.ValidationMessageFor(x => x.Nome)
    </div>

    <div class="form-group">
        <label for="email">E-mail</label>
        <input type="text" asp-for="Email" class="form-control" placeholder="Dogite o e-mail " />
        @Html.ValidationMessageFor(x => x.Email)
    </div>

    <div class="form-group">
        <label for="celular">Celular</label>
        <input type="text" asp-for="Celular" class="form-control" placeholder="Dogite o celular " />
        @Html.ValidationMessageFor(x => x.Celular)
    </div>


    <button type="submit" class="btn btn-primary btn-block">Alterar</button>
    <a class="btn btn-secondary btn-block" asp-controller="contato" asp-action="Index" role="button">Voltar</a>

</form>

AgendaContatos/Views/Contato/Index.cshtml
@model List<ContatoModel>
@{
    ViewData["Title"] = "Lista de Contatos";
}
<div class="text-center">
    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
        <a class="btn btn-primary" role="button" asp-controller="Contato" asp-action="Criar">Adicionar novo Contato</a>
    </div>
    
    <br />

    @if (TempData["MensagemSucesso"] != null)
    {
        <div class="alert alert-success" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" aria-label="Close">X</button>
            @TempData["MensagemSucesso"]
        </div>
    }

    @if (TempData["MensagemErro"] != null)
    {
        <div class="alert alert-danger" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" aria-label="Close">X</button>
            @TempData["MensagemErro"]
        </div>
    }

    <br />

    <h1 class="display-4">Lista de Contatos</h1><br /><br />

    <table id="table-contatos" class="display" style="width:100%">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nome</th>
                <th scope="col">Email</th>
                <th scope="col">Celular</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null && Model.Any())
            {
                foreach (var contato in Model)
                {
                    <tr>
                        <th scope="row">@contato.Id</th>
                        <td>@contato.Nome</td>
                        <td>@contato.Email</td>
                        <td>@contato.Celular</td>
                        <td>
                            <div class="btn-group" role="group">
                                <a role="button" asp-action="Editar" asp-controller="Contato" asp-route-id="@contato.Id" class="btn btn-primary">Editar</a>
                                <a role="button" asp-action="ApagarConfirmacao" asp-controller="Contato" asp-route-id="@contato.Id" class="btn btn-danger">Apagar</a>
                            </div>
                        </td>
                    </tr>
                }
            }
            else
            {
                <tr class="odd"><td valign="top" colspan="5">Nenhum contato encontrado</td></tr>
            }
        </tbody>
    </table>
</div>

AgendaContatos/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Pagina Inicial";
}

<div class="text-center">
    <h1 class="display-4">Bem vindo!</h1>
    <p>Sistema de Controle de Contatos</p>
    
</div>

AgendaContatos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Agenda de Contatos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.13.2/datatables.min.css"/>
 
    

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Agenda de Contatos</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Página Inicial</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contato" asp-action="Index">Contatos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Index">Usuários</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Agenda de Contatos - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.13.2/datatables.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AgendaContatos/Views/Usuario/ApagarConfirmacao.cshtml
@model UsuarioModel
@{
    ViewData["Title"] = "Confirmação apagar Usuário";
}
<div class="text-center">
    <h3>Deseja apagar o Usuário realmente(@Model.Nome)?</h3>
</div>
<a class="btn btn-primary btn-block" role="button" asp-controller="usuario" asp-action="Index">Cancelar exclusão</a>
<a class="btn btn-danger btn-block" role="button" asp-controller="usuario" asp-action="Apagar" asp-route-id="@Model.Id">Confirmar exclusão</a>

AgendaContatos/Views/Usuario/Criar.cshtml
@using AgendaContatos.Enums
@model UsuarioModel

@{
    ViewData["Title"] = "Criar Usuário";
}

<div class="text-center">

    <h1 class="display-4">Cadastrar Usuário</h1>
</div>

<form asp-controller="usuario" asp-action="Criar" method="post">

    <div class="form-group">
        <label for="nome">Nome</label>
        <input type="text" asp-for="Nome" class="form-control" placeholder="Dogite o nome " />
        @Html.ValidationMessageFor(x => x.Nome)
    </div>

    <div class="form-group">
        <label for="email">E-mail</label>
        <input type="text" asp-for="Email" class="form-control" placeholder="Dogite o e-mail " />
        @Html.ValidationMessageFor(x => x.Email)
    </div>

    <div class="form-group">
        <label for="login">Login</label>
        <input type="text" asp-for="Login" class="form-control" placeholder="Dogite o login " />
        @Html.ValidationMessageFor(x => x.Login)
    </div>

    <div class="form-group">
        <label for="perfil">Perfil</label>
        <select asp-for="Perfil" class="form-control">
            <option value="0">Selecione</option>
            <option value="@PerfilEnum.Admin">Administrador</option>
            <option value="@PerfilEnum.Admin">Padrão</option>
        </select>
    </div>

    <div class="form-group">
        <label for="senha">Senha</label>
        <input type="password" asp-for="Senha" class="form-control" placeholder="Dogite a Senha " />
        @Html.ValidationMessageFor(x => x.Senha)
    </div>

    <button type="submit" class="btn btn-primary btn-block">Adicionar</button>
    <a class="btn btn-secondary btn-block" asp-controller="usuario" asp-action="Index" role="button">Voltar</a>


</form>

AgendaContatos/Views/Usuario/Editar.cshtml
@using AgendaContatos.Enums
@model UsuarioModel

@{
    ViewData["Title"] = "Editar Usuário";
}

<div class="text-center">

    <h1 class="display-4">Editar Usuário</h1>
</div>

<form asp-controller="usuario" asp-action="Editar" method="post">

    <input type="hidden" asp-for="Id" />
    <div class="form-group">
        <label for="nome">Nome</label>
        <input type="text" asp-for="Nome" class="form-control" placeholder="Dogite o nome " />
        @Html.ValidationMessageFor(x => x.Nome)
    </div>

    <div class="form-group">
        <label for="email">E-mail</label>
        <input type="text" asp-for="Email" class="form-control" placeholder="Dogite o e-mail " />
        @Html.ValidationMessageFor(x => x.Email)
    </div>

    <div class="form-group">
        <label for="login">Login</label>
        <input type="text" asp-for="Login" class="form-control" placeholder="Dogite o login " />
        @Html.ValidationMessageFor(x => x.Login)
    </div>

    <div class="form-group">
        <label for="perfil">Perfil</label>
        <select asp-for="Perfil" class="form-control">
            <option value="0">Selecione</option>
            <option value="@PerfilEnum.Admin">Administrador</option>
            <option value="@PerfilEnum.Admin">Padrão</option>
        </select>
    </div>

    <button type="submit" class="btn btn-primary btn-block">Editar</button>
    <a class="btn btn-secondary btn-block" asp-controller="usuario" asp-action="Index" role="button">Voltar</a>


</form>

AgendaContatos/Views/Usuario/Index.cshtml
@model List<UsuarioModel>
@{
    ViewData["Title"] = "Lista de Usuários";
}
<div class="text-center">
    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
        <a class="btn btn-primary" role="button" asp-controller="Usuario" asp-action="Criar">Adicionar novo usuário</a>
    </div><br />

    @if (TempData["MensagemSucesso"] != null)
    {
        <div class="alert alert-success" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" aria-label="Close">X</button>
            @TempData["MensagemSucesso"]
        </div>
    }

    @if (TempData["MensagemErro"] != null)
    {
        <div class="alert alert-danger" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" aria-label="Close">X</button>
            @TempData["MensagemErro"]
        </div>
    }

    <br />

    <h1 class="display-4">Lista de Usuários</h1><br /><br />

    <table id="table-usuarios" class="display" style="width:100%">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nome</th>
                <th scope="col">Login</th>
                <th scope="col">Email</th>
                <th scope="col">Data de Cadastro</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null && Model.Any())
            {
                foreach (UsuarioModel usuario in Model)
                {
                    <tr>
                        <th scope="row">@usuario.Id</th>
                        <td>@usuario.Nome</td>
                        <td>@usuario.Login</td>
                        <td>@usuario.Email</td>
                        <td>@usuario.DataCadastro</td>
                        <td>
                            <div class="btn-group" role="group">
                                <a role="button" class="btn btn-primary" asp-route-id="@usuario.Id" asp-controller="Usuario" asp-action="Editar">Editar</a>
                                <a role="button" class="btn btn-danger" asp-route-id="@usuario.Id" asp-controller="Usuario" asp-action="ApagarConfirmacao">Apagar</a>
                            </div>
                        </td>
                    </tr>
                }
            }
            else
            {
                <tr class="odd"><td valign="top" colspan="5">Nenhum usuário encontrado</td></tr>
            }
        </tbody>
    </table>
</div>